info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    product:
      path: /product/**
#    productcomposite:
#      path: /productcomposite/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO